### ISSUE TITLE
Is there any config needed after installation ?

### ISSUE THREAD

**Issue by wazdra** [rafoo/flycheck-dedukti#3]
Hello !
I don't know a lot about Lisp, and Emacs' backend (yet !). I was just wondering, I installed flycheck-dedukti from melpa, and yet, when i'm in a dk file, i only have the general flycheck mode on (C-c ! v says "There are no syntax checkers for this buffer !"). 
Do I have something else to do ? 
Thanks

**Comment by rafoo** [comment]
A config file has indeed been needed since the packaging into melpa (this is discussed here: https://github.com/melpa/melpa/pull/2048).

The following snippet should enable flycheck-mode in Dedukti buffers (assuming dedukti-mode and flycheck-dedukti are installed):

```
(eval-after-load 'dedukti-mode '(progn
  (require 'flycheck-dedukti)
  (add-hook 'dedukti-mode-hook (lambda ()
     (flycheck-select-checker 'dedukti)
     (flycheck-mode)
     ))))
```
